// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAN3KjKDS3gS8XC3-5SDsXFmb7JQ44wts',
    appId: '1:958860601290:web:1180382954e9bf0aead133',
    messagingSenderId: '958860601290',
    projectId: 'zzinc-427c4',
    authDomain: 'zzinc-427c4.firebaseapp.com',
    storageBucket: 'zzinc-427c4.appspot.com',
    measurementId: 'G-MN08EJTLD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrYqCK6s2OBFswW3GAAu6QyYFMXrZFOyI',
    appId: '1:958860601290:android:5ff6ef6c58a6bfe1ead133',
    messagingSenderId: '958860601290',
    projectId: 'zzinc-427c4',
    storageBucket: 'zzinc-427c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdXlVlw_Ph-P93ouuJw47XBhLyzxfnBmU',
    appId: '1:958860601290:ios:4629f111682430ecead133',
    messagingSenderId: '958860601290',
    projectId: 'zzinc-427c4',
    storageBucket: 'zzinc-427c4.appspot.com',
    iosBundleId: 'com.example.zinc',
  );

}